Add L1 flapping tests with more auto-checks, update mans
update static-test man pages
add ldms_status macro
extend ldms_barrier uses in pll testing
add input checking and wait operations for pll and serial versions
add scalable L1 flapping under slurm (pll-ldms-static-test.sh)
add small-scalable L1 flap test case for serial (ldms-static-test.sh)

diff --git a/ldms/scripts/ldms-static-test.sh.in b/ldms/scripts/ldms-static-test.sh.in
--- a/ldms/scripts/ldms-static-test.sh.in
+++ b/ldms/scripts/ldms-static-test.sh.in
@@ -21,6 +21,8 @@ export pkglibdir=${ovis_ldms_pkglibdir}
 export PACKAGE_TARNAME=ovis-ldms
 export docdir=${ovis_ldms_datarootdir}/doc/${PACKAGE_TARNAME}
 export exdir=$docdir
+# default log is debug
+export LOG_LEVEL=DEBUG
 
 if test -z "$ZAP_LIBPATH"; then
 	ZAP_LIBPATH=$ovis_ldms_plugins
@@ -109,8 +111,14 @@ TESTDIR=$2
 
 if test -z "$2"; then
 	TESTDIR=`pwd`/ldmstest/$testname
+	TESTDIR_FAST=/dev/shm/$USER/ldmstest/$testname/$$
+else
+	TESTDIR_FAST=/dev/shm/$USER/$TESTDIR/$$
 fi
+export TESTDIR_FAST
 export TESTDIR
+# TESTDIR must be on a global file system
+# TESTDIR_FAST must be on a node-local memory or nvme
 
 if test -z "$HOST"; then
 	# used for ldms_ls
@@ -136,6 +144,25 @@ function vgoff {
   usevg=0
 }
 
+log_level_list="DEBUG|ERROR|INFO|ALL|QUIET|WARNING|CRITICAL"
+function SET_LOG_LEVEL {
+
+	lvl=$1
+	case $lvl in
+	DEBUG|ERROR|INFO|ALL|QUIET|WARNING|CRITICAL)
+		;;
+	*)
+		echo unknown log level $1
+		echo expected one of $log_level_list
+		bypass=1
+		return 1
+		;;
+	esac
+	export LOG_LEVEL=$lvl
+	echo "LOG_LEVEL=$LOG_LEVEL"
+	return 0
+}
+
 # clear old daemons in the range we're expected and define the
 # port variables.
 did_daemons=0
@@ -156,6 +183,7 @@ function DAEMONS {
 			ln -s ${BUILDDIR}/sbin/ldmsd $LDMSD_RUN/$binname
 		fi
 	done
+	did_daemons=1
 }
 
 # LDMSD number-list launch a daemon for each number
@@ -250,7 +278,15 @@ function LDMSD {
 					if test $loopfile = "0"; then
 						loopfile=$j
 						pfn=`get_prolog_name $loopfile $input`
-						echo "# looped prolog from $pfn" >> $LDMSD_RUN/conf.$i
+						if test -f "$pfn"; then
+							echo "# looped prolog from $pfn" >> $LDMSD_RUN/conf.$i
+						else
+							echo "# prolog $loopfile MISSING" >> $LDMSD_RUN/conf.$i
+							echo "Prolog $loopfile MISSING"
+							echo "$pfn"
+							bypass=1
+							return
+						fi
 					else
 						cat $pfn | sed -e "s/\${j}/$j/g" >> $LDMSD_RUN/conf.$i
 					fi
@@ -258,8 +294,16 @@ function LDMSD {
 			done
 			for pf in $prologs; do
 				pfn=`get_prolog_name $pf $input`
-				echo "# prolog from $pfn" >> $LDMSD_RUN/conf.$i
-				cat $pfn >> $LDMSD_RUN/conf.$i
+				if test -f "$pfn"; then
+					echo "# prolog from $pfn" >> $LDMSD_RUN/conf.$i
+					cat $pfn >> $LDMSD_RUN/conf.$i
+				else
+					echo "# prolog $pf MISSING" >> $LDMSD_RUN/conf.$i
+					echo "Prolog $pf MISSING"
+					echo $pfn
+					bypass=1
+					return
+				fi
 			done
 			echo "# generated from $input.$i" >> $LDMSD_RUN/conf.$i
 			cat $input.$i >> $LDMSD_RUN/conf.$i
@@ -267,21 +311,21 @@ function LDMSD {
 			ldms-reverse-conf.sh $LDMSD_RUN/conf.$i > $LDMSD_RUN/revconf.$i
 			env > $LDMSD_RUN/env.$i
 			if test -n "$GDB"; then
-				echo "run -x ${XPRT}:${ports[$i]}:${XPRTHOST} -c $LDMSD_RUN/conf.$i -l ${LOGDIR}/$i.txt -v DEBUG $LDMSD_EXTRA -r $LDMSD_PIDFILE.$i"
+				echo "run -x ${XPRT}:${ports[$i]}:${XPRTHOST} -c $LDMSD_RUN/conf.$i -l ${LOGDIR}/$i.txt -v $LOG_LEVEL $LDMSD_EXTRA -r $LDMSD_PIDFILE.$i"
 				gdb ldmsd.${ports[$i]}
 			else
 				echo $wrap ldmsd.${ports[$i]} \
 					-x ${XPRT}:${ports[$i]}${XPRTHOST} \
 					-c $LDMSD_RUN/conf.$i \
 					-l ${LOGDIR}/$i.txt \
-					-v DEBUG $LDMSD_EXTRA \
+					-v $LOG_LEVEL $LDMSD_EXTRA \
 					-r $LDMSD_PIDFILE.$i \
 				"2>&1 > ${LOGDIR}/$i.stdio &" > $LDMSD_RUN/start.$i
 				$wrap ldmsd.${ports[$i]} \
 					-x ${XPRT}:${ports[$i]}${XPRTHOST} \
 					-c $LDMSD_RUN/conf.$i \
 					-l ${LOGDIR}/$i.txt \
-					-v DEBUG $LDMSD_EXTRA \
+					-v $LOG_LEVEL $LDMSD_EXTRA \
 					-r $LDMSD_PIDFILE.$i \
 					2>&1 > ${LOGDIR}/$i.stdio &
 			fi
@@ -298,7 +342,7 @@ function LDMSD {
 					-x ${XPRT}:${ports[$i]}${XPRTHOST} \
 					-c $LDMSD_RUN/conf.$i \
 					-l ${LOGDIR}/$i.txt \
-					-v DEBUG $LDMSD_EXTRA \
+					-v $LOG_LEVEL $LDMSD_EXTRA \
 					-r $LDMSD_PIDFILE.$i \
 					"2>&1 > ${LOGDIR}/$i.stdio &" \
 					> $LDMSD_RUN/start.$i
@@ -306,7 +350,7 @@ function LDMSD {
 					-x ${XPRT}:${ports[$i]}${XPRTHOST} \
 					-c $LDMSD_RUN/conf.$i \
 					-l ${LOGDIR}/$i.txt \
-					-v DEBUG $LDMSD_EXTRA \
+					-v $LOG_LEVEL $LDMSD_EXTRA \
 					-r $LDMSD_PIDFILE.$i \
 					2>&1 > ${LOGDIR}/$i.stdio &
 			else
@@ -315,13 +359,13 @@ function LDMSD {
 				echo "#" > $LDMSD_RUN/revconf.$i
 				echo ldmsd.${ports[$i]} -x ${XPRT}:${ports[$i]}${XPRTHOST} \
 					-l ${LOGDIR}/$i.txt \
-					-v DEBUG \
+					-v $LOG_LEVEL \
 					-r $LDMSD_PIDFILE.$i \
 					"2>&1 > ${LOGDIR}/$i.stdio &" \
 					> $LDMSD_RUN/start.$i
 				ldmsd.${ports[$i]} -x ${XPRT}:${ports[$i]}${XPRTHOST} \
 					-l ${LOGDIR}/$i.txt \
-					-v DEBUG \
+					-v $LOG_LEVEL \
 					-r $LDMSD_PIDFILE.$i \
 					2>&1 > ${LOGDIR}/$i.stdio &
 			fi
@@ -329,10 +373,11 @@ function LDMSD {
 		# assume gnu sleep and bc exist, because usleep deprecated
 		#sleep $(echo "0.000001 * $startwait" |bc)
 		nwait=0
+		nwait_max=$(($startwait / 100000)) ; # tenth second ticks
 		while ! test -f $LDMSD_PIDFILE.$i; do
 			((nwait++))
 			sleep 0.1
-			if test $nwait -gt 100; then
+			if test $nwait -ge $nwait_max; then
 				echo FAIL: failed to start $i. check ${LOGDIR}/$i.txt
 				bypass=1
 				break;
@@ -429,8 +474,203 @@ function LDMS_STATUS {
 	done
 }
 
+function LDMS_AGG_WAIT {
+	# wait until all daemons given have been seen to have the schema named present
+	# on the agg daemon given. Set names must be localhost${i}/$schema
+	# LDMS_AGG_WAIT agg-daemon agg-timeout schema set-timeout daemon_number*
+	# timeouts are integer seconds to wait. 0 or less is infinite wait.
+	# checking of the agg daemon is performed by the process rank which launched it,
+	# while others wait on the result.
+	# aggregator connect retry is 0.5 sec
+        # set lookup retries are 0.2 sec
+	if test "$bypass" = "1"; then
+		return 0
+	fi
+	agg_retry_interval=0.5
+	set_retry_interval=0.2
+	aggd=$1
+	agg_timeout=$2
+	schema=$3
+	set_timeout=$4
+	shift
+	shift
+	shift
+	shift
+	# wait on agg to appear
+	if test $agg_timeout -le 0; then
+		agg_timeout=1000000000
+	fi
+	# do the repeated checking
+	agg_tend=$(( $(date +%s) + $agg_timeout))
+	while /bin/true; do
+		sleep $agg_retry_interval
+		if test $(date +%s) -gt $agg_tend; then
+			echo timeout connecting to aggregator daemon $aggd
+			bypass=1
+			return 1 ; # all others will timeout
+		fi
+		if test -n "$PORT"; then
+			iport=$PORT
+		else
+			iport=${ports[$aggd]}
+		fi
+		if ! test -f "$LDMSD_PIDFILE.$aggd"; then
+			continue
+		fi
+		ihost=localhost
+		if ldms_ls -x $XPRT -p $iport -h $ihost -S set_dummy > /dev/null; then
+			echo found aggregator $myproc at $(date +%s.%N)
+			break
+		fi
+	done
+
+	declare -a lswait
+	# build target set list
+	for i in $*; do
+		lswait[$i]=1
+	done
+	if test $set_timeout -le 0; then
+		set_timeout=1000000000
+	fi
+	set_tend=$(( $(date +%s) + $set_timeout))
+	if test -n "$PORT"; then
+		iport=$PORT
+	else
+		iport=${ports[$aggd]}
+	fi
+	ihost=localhost
+	while test ${#lswait[@]} -gt 0; do
+		sleep $set_retry_interval
+		if test $(date +%s) -gt $set_tend; then
+			tnow=$(date +%s.%N)
+			break
+		fi
+		echo waiting ${#lswait[@]} sets to appear
+		ofile=$TESTDIR_FAST/ldms_agg_wait.out
+		while test ${#lswait[@]} -gt 0; do
+			timecheck=$(date +%s)
+			if test $timecheck -gt $set_tend; then
+				echo LDMS_AGG_WAIT sets check timed out at $timecheck
+				break
+			fi
+			if ! test -f "$LDMSD_PIDFILE.$aggd"; then
+				echo LDMS_AGG_WAIT: pid of agg disappeared at $timecheck
+				break; # agg died? will it restart?
+			fi
+			if ldms_ls -x $XPRT -p $iport -h $ihost -S $schema > $ofile; then
+				if ! test -f $ofile; then
+					echo LDMS_AGG_WAIT: failed ldms_ls at $timecheck
+					break 2
+				fi
+				tnow=$(date +%s.%N)
+				nl=$(sed -e 's/^ldms.*//' -e 's%^localhost%%' -e  "s%/${schema}.*%%" $ofile)
+				/bin/rm -f $ofile
+				for i in $nl; do
+					if test x${lswait[${i}]} = x1; then
+						echo "found set from daemon $i at $tnow";
+						unset -v lswait[$i];
+					fi
+				done
+			fi
+		done
+	done
+	if test ${#lswait[@]} -gt 0; then
+		echo "LDMS_AGG_WAIT missing daemon list: ${!lswait[@]}"
+
+		echo "LDMS_AGG_WAIT timed out at $tnow waiting for daemon count: ${#lswait[@]}"
+		bypass=1
+		# not starting wait_all, so others will timeout.
+	fi
+}
+
+function LDMS_AGG_WAIT_SET_COUNT {
+	# wait until daemon given has no more than COUNT sets.
+	# LDMS_AGG_WAITSET_COUNT agg-daemon agg_timeout set-count set_timeout
+	# timeouts are integer seconds to wait. 0 or less is infinite wait.
+	# retry at agg is 0.5 sec
+	# checking of the agg daemon is performed by the process instance which launched it,
+	# while others wait on the result.
+	# could apply $* to ldms_ls as a filter on the count, but have not yet.
+	if test "$bypass" = "1"; then
+		return 0
+	fi
+	agg_retry_interval=0.5
+	set_retry_interval=0.5
+	aggd=$1
+	agg_timeout=$2
+	set_count=$3
+	set_timeout=$4
+	shift
+	shift
+	shift
+	shift
+	# do the repeated checking of aggd
+	# wait on agg to appear
+	if test $agg_timeout -le 0; then
+		agg_timeout=1000000000
+	fi
+	agg_tend=$(( $(date +%s) + $agg_timeout))
+	if test -n "$PORT"; then
+		iport=$PORT
+	else
+		iport=${ports[$aggd]}
+	fi
+	ihost=localhost
+	while /bin/true; do
+		sleep $agg_retry_interval
+		if test $(date +%s) -gt $agg_tend; then
+			echo timeout connecting to aggregator daemon $aggd
+			bypass=1
+			return 1
+		fi
+		if ! test -f "$LDMSD_PIDFILE.$aggd"; then
+			continue
+		fi
+		if ldms_ls -x $XPRT -p $iport -h $ihost -S set_dummy > /dev/null; then
+			echo found aggregator $i at $(date +%s.%N)
+			break
+		fi
+	done
+
+	if test $set_timeout -le 0; then
+		set_timeout=1000000000
+	fi
+	set_tend=$(( $(date +%s) + $set_timeout))
+	echo waiting drop to $set_count sets
+	while /bin/true; do
+		sleep $set_retry_interval
+		if test $(date +%s) -gt $set_tend; then
+			tnow=$(date +%s.%N)
+			break
+		fi
+		ofile=$TESTDIR_FAST/ldms_agg_wait_set_count.out
+		if ! test -f "$LDMSD_PIDFILE.$aggd"; then
+			break; # agg died?
+		fi
+		/bin/rm -f $ofile
+		if ldms_ls -x $XPRT -p $iport -h $ihost > $ofile; then
+			nl=$(grep ^localhost $ofile | wc -l)
+			/bin/rm $ofile
+			if test $nl -le $set_count; then
+				tnow=$(date +%s.%N)
+				echo "set count dropped to or below $set_count at $tnow";
+				return 0
+			fi
+		fi
+	done
+	echo "LDMS_AGG_WAIT_SET_COUNT: timeout at $tnow with still $nl sets remaining:"
+	ldms_ls -x $XPRT -p $iport -h $ihost
+	# we don't launch wait_all here, so testleader never appears and all others
+	# hit the timeout error.
+	bypass=1
+	return 1
+}
+
 # FILECNT_LDMSD num list
 function FILECNT_LDMSD {
+	if test "$bypass" = "1"; then
+		return 0
+	fi
 	for i in $*; do
 		if test -f $LDMSD_PIDFILE.$i; then
 			dpid=$(cat $LDMSD_PIDFILE.$i)
@@ -453,7 +693,6 @@ function KILL_LDMSD {
 			KILL_LDMSD_STRICT=1
 			continue
 		fi
-
 		if test -f $LDMSD_PIDFILE.$i; then
 			if test -n "$PORT"; then
 				iport=$PORT
@@ -579,7 +818,7 @@ SECRET=$SOCKDIR/secret
 export TSAN_OPTIONS=verbosity=1:log_path=$LOGDIR:strip_path_prefix=$prefix
 export ASAN_OPTIONS=verbosity=1:log_path=$LOGDIR:detect_stack_use_after_return=1:detect_leaks=1:strip_path_prefix=$prefix
 export LDMSD_RUN=${TESTDIR}/run
-mkdir -p $STOREDIR $SOCKDIR $LOGDIR $LDMSD_RUN
+mkdir -p $STOREDIR $SOCKDIR $LOGDIR $LDMSD_RUN $TESTDIR_FAST
 echo "secretword="`openssl rand -hex 16` > $SECRET
 export LDMS_AUTH_FILE=$SECRET
 chmod go-rwx $SECRET
