fix missing prolog file error handling

diff --git a/ldms/scripts/pll-ldms-static-test.sh.in b/ldms/scripts/pll-ldms-static-test.sh.in
--- a/ldms/scripts/pll-ldms-static-test.sh.in
+++ b/ldms/scripts/pll-ldms-static-test.sh.in
@@ -117,9 +117,8 @@ function get_prolog_name () {
 		fi
 	fi
 	if ! test -f $rfile -a -r $rfile; then
-		echo "FAIL: $myproc: cannot find test prolog $pfile in . $exdir/examples/slurm-test or next to $basefile."
+		echo "FAIL: $myproc: cannot find test prolog $pfile in . $exdir/examples/slurm-test or next to $basefile." >&2
 		rfile=""
-		exit 1
 	fi
 	echo $rfile
 }
@@ -315,16 +314,28 @@ function LDMSD {
 					if test $loopfile = "0"; then
 						loopfile=$j
 						pfn=`get_prolog_name $loopfile $input`
-						echo "# looped prolog from $pfn" >> $LDMSD_RUN/conf.$i
+						if test -n "$pfn"; then
+							echo "# looped prolog from $pfn" >> $LDMSD_RUN/conf.$i
+						else
+							exit 1
+						fi
 					else
-						cat $pfn | sed -e "s/\${j}/$j/g" >> $LDMSD_RUN/conf.$i
+						if test -n "$pfn"; then
+							cat $pfn | sed -e "s/\${j}/$j/g" >> $LDMSD_RUN/conf.$i
+						else
+							exit 1
+						fi
 					fi
 				done
 			done
 			for pf in $prologs; do
 				pfn=`get_prolog_name $pf $input`
-				echo "# prolog from $pfn" >> $LDMSD_RUN/conf.$i
-				cat $pfn >> $LDMSD_RUN/conf.$i
+				if test -n "$pfn"; then
+					echo "# prolog from $pfn" >> $LDMSD_RUN/conf.$i
+					cat $pfn >> $LDMSD_RUN/conf.$i
+				else
+					exit 1
+				fi
 			done
 			echo "# generated from $input.$insuff" >> $LDMSD_RUN/conf.$i
 			cat $input.$insuff >> $LDMSD_RUN/conf.$i
