Add L1 flapping tests with more auto-checks, update mans
update static-test man pages
add ldms_status macro
extend ldms_barrier uses in pll testing
add input checking and wait operations for pll and serial versions
add scalable L1 flapping under slurm (pll-ldms-static-test.sh)
add small-scalable L1 flap test case for serial (ldms-static-test.sh)

diff --git a/ldms/scripts/pll-ldms-static-test.sh.in b/ldms/scripts/pll-ldms-static-test.sh.in
--- a/ldms/scripts/pll-ldms-static-test.sh.in
+++ b/ldms/scripts/pll-ldms-static-test.sh.in
@@ -41,6 +41,9 @@ export LDMSD_PLUGIN_LIBPATH
 export LD_LIBRARY_PATH=${ovis_ldms_plugins_rpath}:${BUILDDIR}/lib:${exec_prefix}/lib:$ovis_ldms_plugins:$LD_LIBRARY_PATH
 export PYTHONPATH=${ovis_ldms_pythondir}:$PYTHONPATH
 
+export LDMSD_LOG_DATE_TIME=1
+export LDMSD_LOG_TIME_SEC=1
+
 function clusage {
 cat << EOF
 $0: usage:
@@ -50,7 +53,7 @@ $0 -b <input_file>
 $0 <input_file> [test_dir]
 	-h produces help message
 	-l produces list of canned test names
-See man pll-ldms-static-test(8) for details.
+See man ldms_pll-ldms-static-test(8) for details.
 EOF
 }
 input=$1
@@ -388,7 +391,15 @@ function LDMSD {
 					if test $loopfile = "0"; then
 						loopfile=$j
 						pfn=`get_prolog_name $loopfile $input`
-						echo "# looped prolog from $pfn" >> $LDMSD_RUN/conf.$i
+						if test -f "$pfn"; then
+							echo "# looped prolog from $pfn" >> $LDMSD_RUN/conf.$i
+						else
+							echo "# prolog $loopfile MISSING" >> $LDMSD_RUN/conf.$i
+							echo "Prolog $loopfile MISSING"
+							echo "$pfn"
+							bypass=1
+							return
+						fi
 					else
 						cat $pfn | sed -e "s/\${j}/$j/g" >> $LDMSD_RUN/conf.$i
 					fi
@@ -396,8 +407,16 @@ function LDMSD {
 			done
 			for pf in $prologs; do
 				pfn=`get_prolog_name $pf $input`
-				echo "# prolog from $pfn" >> $LDMSD_RUN/conf.$i
-				cat $pfn >> $LDMSD_RUN/conf.$i
+				if test -f "$pfn"; then
+					echo "# prolog from $pfn" >> $LDMSD_RUN/conf.$i
+					cat $pfn >> $LDMSD_RUN/conf.$i
+				else
+					echo "# prolog $pf MISSING" >> $LDMSD_RUN/conf.$i
+					echo "Prolog $pf MISSING"
+					echo $pfn
+					bypass=1
+					return
+				fi
 			done
 			echo "# generated from $input.$insuff" >> $LDMSD_RUN/conf.$i
 			cat $input.$insuff >> $LDMSD_RUN/conf.$i
@@ -458,15 +477,19 @@ function LDMSD {
 			fi
 		fi
 		# assume gnu sleep and bc exist, because usleep deprecated
-		sleep $(echo "0.000001 * $startwait" |bc)
-
-#	if ! test -f $LDMSD_PIDFILE.$i; then
-#		echo FAIL: $myproc: failed to start $i $XPRTHOST. check ${LOGDIR}/$i.txt
-#		#bypass=1
-#		break;
-#	fi
+		#sleep $(echo "0.000001 * $startwait" |bc)
+		nwait=0
+		nwait_max=$(($startwait / 100000)) ; # tenth second ticks
+		while ! test -f $LDMSD_PIDFILE.$i; do
+			((nwait++))
+			sleep 0.1
+			if test $nwait -ge $nwait_max; then
+				echo FAIL: failed to start $i. check ${LOGDIR}/$i.txt
+				# bypass=1
+				break;
+			fi
+		done
 	done
-
 }
 
 # MESSAGE print arguments to output
@@ -522,6 +545,66 @@ function LDMS_LS {
 	done
 }
 
+#
+function LDMS_STATUS {
+	if test "$bypass" = "1"; then
+		return 0
+	fi
+	nodes=$1
+	shift
+	for i in $nodes; do
+		if test $i -ne $myproc; then
+			continue
+		fi
+		if test "$usevg" = "1"; then
+			if test -z "$VG"; then
+				XVG=valgrind
+			else
+				XVG=$VG
+			fi
+			if test -n "LDMSNET"; then
+				XVGSUFF=".$LDMSNET"
+			fi
+			if test -z "$VGARGS"; then
+				VGARGS="-v --log-file=${LOGDIR}/vgls.$i$VGTAG.%p"
+			else
+				XVGARGS="-v --log-file=${LOGDIR}/vgls.$i$VGTAG.%p$XVGSUFF $VGARGS"
+			fi
+			wrap="$XVG $XVGARGS"
+		else
+			wrap=""
+		fi
+		if ! test -f "$LDMSD_PIDFILE.$i"; then
+			echo FAIL: $myproc: ls of missing daemon $i skipped. check ${LOGDIR}/$i.txt
+			bypass=1
+			break;
+		fi
+		if test -n "$PORT"; then
+			iport=$PORT
+		else
+			iport=${ports[$i]}
+		fi
+		ihost=${hosts[$i]}
+		echo "$myproc: echo status | $wrap ldmsd_controller -h $ihost -x $XPRT -p $iport"
+		echo status | $wrap ldmsd_controller  -h $ihost -x $XPRT -p $iport
+	done
+}
+
+function BEST_DELAY {
+	# for single node tests, we can do better than sleep by checking
+	# with ss for sockets to clear.
+	if test "$bypass" = "1"; then
+		return 0
+	fi
+	bwait=$1
+	if test $SLURM_JOB_NUM_NODES = "1"; then
+		MESSAGE "waiting up to $bwait seconds for time_waits to clear"
+		SOCKWAIT $portbase $bwait
+	else
+		SLEEP $bwait
+	fi
+}
+
 function SOCKWAIT {
 	# wait until nothing local is holding onto myport (return 0)
 	# or until timeout seconds go by (return 1).
@@ -533,12 +616,14 @@ function SOCKWAIT {
         for i in $(seq $timeout); do
                 y=$(ss -Hon state all "( sport = :$myport )" |wc -l)
                 if test $y = "0"; then
-                        echo done
+                        echo done in $i seconds
                         return 0
                 fi
                 echo -n .
                 sleep 1
         done
+	MESSAGE "port $myport still busy. expect problems.  ss said:"
+	ss -Hon state all "( sport = :$myport )"
         return 1 ; # something still stuck
 }
 
@@ -565,6 +650,7 @@ function WAIT_ALL {
 		if test $i -ne $myproc; then
 			continue
 		fi
+		set -x
 		ldms_barrier \
 			--client-tag $i \
 			--max-clients $count \
@@ -576,6 +662,7 @@ function WAIT_ALL {
 			$BARRIER_VERBOSE \
 			$*
 		stat=$?
+		set +x
 		if ! test $stat = "0"; then
 			MESSAGE barrier fail $stat
 			bypass=1
@@ -583,6 +670,8 @@ function WAIT_ALL {
 		return $stat
 	done
 	if test $lead = $myproc; then
+		wait_start=$(date +%s)
+		set -x
 		ldms_barrier \
 			-l \
 			--client-tag $lead \
@@ -595,6 +684,8 @@ function WAIT_ALL {
 			$BARRIER_VERBOSE \
 			$*
 		stat=$?
+		MESSAGE wait-lead-time $(( $(date +%s) - $wait_start))
+		set +x
 		if ! test $stat = "0"; then
 			MESSAGE barrier fail $stat
 			bypass=1
@@ -754,7 +845,6 @@ function LDMS_AGG_WAIT {
 	if test $agg_timeout -le 0; then
 		agg_timeout=1000000000
 	fi
-	set -x
 	# do the repeated checking from just aggd driver
 	testleader=$aggd
 	if test "x$myproc" = "x$testleader"; then
@@ -776,7 +866,7 @@ function LDMS_AGG_WAIT {
 			fi
 			ihost=${hosts[$aggd]}
 			if ldms_ls -x $XPRT -p $iport -h $ihost -S set_dummy > /dev/null; then
-				echo found aggregator $i at $(date +%s.%N)
+				echo found aggregator $myproc at $(date +%s.%N)
 				break
 			fi
 		done
@@ -928,7 +1018,7 @@ function LDMS_AGG_WAIT_SET_COUNT {
 		return 1
 	else
 		echo "LDMS_AGG_WAIT_SET_COUNT: rank $testleader is performing checks."
-		WAIT_ALL $(( $set_timeout + $agg_timeout)) $ALL_DAEMONS
+		WAIT_ALL $(( $set_timeout + $agg_timeout + 60)) $ALL_DAEMONS
 	fi
 }
 
@@ -982,6 +1072,9 @@ function LDMS_CPU_GRIND {
 
 # FILECNT_LDMSD num list
 function FILECNT_LDMSD {
+	if test "$bypass" = "1"; then
+		return 0
+	fi
 	for i in $*; do
 		if test $i -ne $myproc; then
 			continue
@@ -991,7 +1084,8 @@ function FILECNT_LDMSD {
 			dts=$(date +%s)
 			/bin/ls /proc/$dpid/fd -l > $LDMSD_PIDFILE.$i.cnt.$dts
 			filecnt=$(wc -l $LDMSD_PIDFILE.$i.cnt.$dts | sed -e 's/ .*//')
-			echo "$myproc: filecnt=$filecnt"
+			echo "$myproc: FileCount=$filecnt"
+			egrep '(Threads|VmRSS|VmSize)' /proc/$dpid/status |sed -e 's/:[[:space:]]*/=/' -e "s/^/$myproc: /"
 			mv $LDMSD_PIDFILE.$i.cnt.$dts $LDMSD_PIDFILE.$i.cnt.$dts.$filecnt
 		else
 			echo $myproc: filecnt cannot find pidfile for $i
